import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {
    RecoilRoot,
    atom,
    selector,
    useRecoilState,
    useRecoilValue,
} from 'recoil'
import { RecoilJsDemo } from '../components/recoil/RecoilTeste'

const Home: NextPage = () => {
    return (
        <section>
            <Head>
                <title>Boilerplate Kaspa | Next Js</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link
                    rel="icon"
                    href="/favicon.ico"
                />
            </Head>

            <main>
                <h1>Boilerplate NextJs</h1>
                <p> Next-Auth </p>
                <p> RecoilJs </p>
                <p> ESLint | Prettier </p>
                <p> Husky </p>
                <p> SWR </p>
                <div>
                    <h2> Recoil. JS Demo </h2>
                    <RecoilRoot>
                        <RecoilJsDemo />
                    </RecoilRoot>
                </div>
            </main>
            <footer>
                <h3> FOOTER </h3>
                <p> footer section </p>
            </footer>
        </section>
    )
}

export default Home
